export const my = [
    'ADAUSDT',
    'AXSUSDT',
    'BTCUSDT',
    'CELOUSDT',
    'DOGEUSDT',
    'DOTUSDT',
    "ETHUSDT",
    'FTMUSDT',
    'FILUSDT',
    'LUNAUSDT',
    'LTCUSDT',
    'MATICUSDT',
    'SOLUSDT',
    'XRPUSDT',
];